import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': "Don't have an account?",
    'auth.signingIn': 'Signing in...',
    'auth.signingUp': 'Creating account...',
    'auth.logout': 'Logout',
    'dashboard.title': 'Dashboard',
    'dashboard.netBalance': 'Net Balance',
    'dashboard.totalIncome': 'Total Income',
    'dashboard.totalExpense': 'Total Expense',
    'dashboard.transactions': 'Transactions',
    'dashboard.noTransactions': 'No transactions yet',
    'dashboard.quickActions': 'Quick Actions',
    'wallet.title': 'Wallets',
    'wallet.create': 'Create Wallet',
    'wallet.name': 'Wallet Name',
    'wallet.description': 'Description',
    'wallet.select': 'Select Wallet',
    'wallet.creating': 'Creating...',
    'wallet.noWallets': 'No wallets yet. Create one to get started!',
    'transaction.add': 'Add Transaction',
    'transaction.edit': 'Edit Transaction',
    'transaction.type': 'Type',
    'transaction.income': 'Income',
    'transaction.expense': 'Expense',
    'transaction.amount': 'Amount',
    'transaction.category': 'Category',
    'transaction.description': 'Description',
    'transaction.date': 'Date',
    'transaction.saving': 'Saving...',
    'transaction.save': 'Save',
    'transaction.delete': 'Delete',
    'transaction.cancel': 'Cancel',
    'transaction.search': 'Search transactions...',
    'category.salary': 'Salary',
    'category.business': 'Business',
    'category.investment': 'Investment',
    'category.other': 'Other',
    'category.food': 'Food',
    'category.transport': 'Transport',
    'category.shopping': 'Shopping',
    'category.bills': 'Bills',
    'category.entertainment': 'Entertainment',
    'category.transfer': 'Transfer',
    'chart.incomeVsExpense': 'Income vs Expense',
    'chart.cashflow': 'Cashflow Trend',
    'chart.categoryBreakdown': 'Category Breakdown',
    'chart.monthlyGrowth': 'Monthly Growth Rate',
    'chart.walletComparison': 'Wallet Comparison',
    'chart.monthly': 'Monthly',
    'chart.daily': 'Daily',
    'filter.dateRange': 'Date Range',
    'filter.category': 'Category',
    'filter.all': 'All',
    'reports.title': 'Reports',
    'reports.filters': 'Filters',
    'reports.wallet': 'Wallet',
    'reports.allWallets': 'All Wallets',
    'reports.allCategories': 'All Categories',
    'reports.allTypes': 'All Types',
    'reports.type': 'Type',
    'reports.startDate': 'Start Date',
    'reports.endDate': 'End Date',
    'reports.totalIncome': 'Total Income',
    'reports.totalExpense': 'Total Expense',
    'reports.netBalance': 'Net Balance',
    'reports.downloadExcel': 'Download Excel',
    'reports.downloadPDF': 'Download PDF',
    'reports.noTransactions': 'No transactions found',
    'filter.last7days': 'Last 7 Days',
    'filter.last40days': 'Last 40 Days',
    'filter.last60days': 'Last 60 Days',
    'filter.last90days': 'Last 90 Days',
    'filter.custom': 'Custom Range',
    'admin.title': 'Admin Panel',
    'admin.users': 'User Management',
    'admin.wallets': 'All Wallets',
    'admin.transactions': 'All Transactions',
    'admin.roles': 'User Roles',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.createdAt': 'Created At',
    'admin.actions': 'Actions',
    'admin.makeAdmin': 'Make Admin',
    'admin.removeAdmin': 'Remove Admin',
    'admin.totalUsers': 'Total Users',
    'admin.totalWallets': 'Total Wallets',
    'admin.totalTransactions': 'Total Transactions',
    'admin.owner': 'Owner',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.darkMode': 'Dark Mode',
    'common.lightMode': 'Light Mode',
    'common.home': 'Home',
    // Transfer
    'transfer.title': 'Transfer Between Wallets',
    'transfer.from': 'From Wallet',
    'transfer.to': 'To Wallet',
    'transfer.amount': 'Transfer Amount',
    'transfer.submit': 'Transfer',
    'transfer.transferring': 'Transferring...',
    'transfer.success': 'Transfer completed successfully!',
    'transfer.button': 'Transfer',
    // Budget
    'budget.title': 'Budget',
    'budget.add': 'Set Budget',
    'budget.category': 'Category',
    'budget.amount': 'Budget Limit',
    'budget.spent': 'spent',
    'budget.remaining': 'remaining',
    'budget.over': 'over budget',
    'budget.save': 'Save Budget',
    'budget.saving': 'Saving...',
    'budget.nobudgets': 'No budgets set yet',
    // Savings Goals
    'goals.title': 'Savings Goals',
    'goals.add': 'Add Goal',
    'goals.name': 'Goal Name',
    'goals.target': 'Target Amount',
    'goals.current': 'Current Amount',
    'goals.deadline': 'Deadline',
    'goals.deposit': 'Deposit',
    'goals.withdraw': 'Withdraw',
    'goals.progress': 'Progress',
    'goals.save': 'Save Goal',
    'goals.saving': 'Saving...',
    'goals.nogoals': 'No savings goals yet',
    'goals.depositAmount': 'Deposit Amount',
    'goals.completed': 'Completed!',
  },
  id: {
    'auth.signIn': 'Masuk',
    'auth.signUp': 'Daftar',
    'auth.email': 'Email',
    'auth.password': 'Kata Sandi',
    'auth.fullName': 'Nama Lengkap',
    'auth.haveAccount': 'Sudah punya akun?',
    'auth.noAccount': 'Belum punya akun?',
    'auth.signingIn': 'Masuk...',
    'auth.signingUp': 'Membuat akun...',
    'auth.logout': 'Keluar',
    'dashboard.title': 'Dasbor',
    'dashboard.netBalance': 'Saldo Bersih',
    'dashboard.totalIncome': 'Total Pendapatan',
    'dashboard.totalExpense': 'Total Pengeluaran',
    'dashboard.transactions': 'Transaksi',
    'dashboard.noTransactions': 'Belum ada transaksi',
    'dashboard.quickActions': 'Aksi Cepat',
    'wallet.title': 'Dompet',
    'wallet.create': 'Buat Dompet',
    'wallet.name': 'Nama Dompet',
    'wallet.description': 'Deskripsi',
    'wallet.select': 'Pilih Dompet',
    'wallet.creating': 'Membuat...',
    'wallet.noWallets': 'Belum ada dompet. Buat satu untuk memulai!',
    'transaction.add': 'Tambah Transaksi',
    'transaction.edit': 'Edit Transaksi',
    'transaction.type': 'Tipe',
    'transaction.income': 'Pendapatan',
    'transaction.expense': 'Pengeluaran',
    'transaction.amount': 'Jumlah',
    'transaction.category': 'Kategori',
    'transaction.description': 'Deskripsi',
    'transaction.date': 'Tanggal',
    'transaction.saving': 'Menyimpan...',
    'transaction.save': 'Simpan',
    'transaction.delete': 'Hapus',
    'transaction.cancel': 'Batal',
    'transaction.search': 'Cari transaksi...',
    'category.salary': 'Gaji',
    'category.business': 'Bisnis',
    'category.investment': 'Investasi',
    'category.other': 'Lainnya',
    'category.food': 'Makanan',
    'category.transport': 'Transportasi',
    'category.shopping': 'Belanja',
    'category.bills': 'Tagihan',
    'category.entertainment': 'Hiburan',
    'category.transfer': 'Transfer',
    'chart.incomeVsExpense': 'Pendapatan vs Pengeluaran',
    'chart.cashflow': 'Tren Arus Kas',
    'chart.categoryBreakdown': 'Rincian Kategori',
    'chart.monthlyGrowth': 'Tingkat Pertumbuhan Bulanan',
    'chart.walletComparison': 'Perbandingan Dompet',
    'chart.monthly': 'Bulanan',
    'chart.daily': 'Harian',
    'filter.dateRange': 'Rentang Tanggal',
    'filter.category': 'Kategori',
    'filter.all': 'Semua',
    'reports.title': 'Laporan',
    'reports.filters': 'Filter',
    'reports.wallet': 'Dompet',
    'reports.allWallets': 'Semua Dompet',
    'reports.allCategories': 'Semua Kategori',
    'reports.allTypes': 'Semua Tipe',
    'reports.type': 'Tipe',
    'reports.startDate': 'Tanggal Mulai',
    'reports.endDate': 'Tanggal Akhir',
    'reports.totalIncome': 'Total Pendapatan',
    'reports.totalExpense': 'Total Pengeluaran',
    'reports.netBalance': 'Saldo Bersih',
    'reports.downloadExcel': 'Unduh Excel',
    'reports.downloadPDF': 'Unduh PDF',
    'reports.noTransactions': 'Tidak ada transaksi',
    'filter.last7days': '7 Hari Terakhir',
    'filter.last40days': '40 Hari Terakhir',
    'filter.last60days': '60 Hari Terakhir',
    'filter.last90days': '90 Hari Terakhir',
    'filter.custom': 'Rentang Khusus',
    'admin.title': 'Panel Admin',
    'admin.users': 'Manajemen Pengguna',
    'admin.wallets': 'Semua Dompet',
    'admin.transactions': 'Semua Transaksi',
    'admin.roles': 'Peran Pengguna',
    'admin.email': 'Email',
    'admin.role': 'Peran',
    'admin.createdAt': 'Dibuat Pada',
    'admin.actions': 'Tindakan',
    'admin.makeAdmin': 'Jadikan Admin',
    'admin.removeAdmin': 'Hapus Admin',
    'admin.totalUsers': 'Total Pengguna',
    'admin.totalWallets': 'Total Dompet',
    'admin.totalTransactions': 'Total Transaksi',
    'admin.owner': 'Pemilik',
    'common.loading': 'Memuat...',
    'common.error': 'Kesalahan',
    'common.success': 'Berhasil',
    'common.darkMode': 'Mode Gelap',
    'common.lightMode': 'Mode Terang',
    'common.home': 'Beranda',
    'transfer.title': 'Transfer Antar Dompet',
    'transfer.from': 'Dari Dompet',
    'transfer.to': 'Ke Dompet',
    'transfer.amount': 'Jumlah Transfer',
    'transfer.submit': 'Transfer',
    'transfer.transferring': 'Mentransfer...',
    'transfer.success': 'Transfer berhasil!',
    'transfer.button': 'Transfer',
    'budget.title': 'Anggaran',
    'budget.add': 'Atur Anggaran',
    'budget.category': 'Kategori',
    'budget.amount': 'Batas Anggaran',
    'budget.spent': 'terpakai',
    'budget.remaining': 'tersisa',
    'budget.over': 'melebihi anggaran',
    'budget.save': 'Simpan Anggaran',
    'budget.saving': 'Menyimpan...',
    'budget.nobudgets': 'Belum ada anggaran',
    'goals.title': 'Target Tabungan',
    'goals.add': 'Tambah Target',
    'goals.name': 'Nama Target',
    'goals.target': 'Jumlah Target',
    'goals.current': 'Jumlah Saat Ini',
    'goals.deadline': 'Tenggat Waktu',
    'goals.deposit': 'Setor',
    'goals.withdraw': 'Tarik',
    'goals.progress': 'Progres',
    'goals.save': 'Simpan Target',
    'goals.saving': 'Menyimpan...',
    'goals.nogoals': 'Belum ada target tabungan',
    'goals.depositAmount': 'Jumlah Setoran',
    'goals.completed': 'Tercapai!',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
